# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(378, 220)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1080, 600))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")

        self.fileEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fileEdit.setReadOnly(True)
        self.fileEdit.setObjectName("fileEdit")
        self.gridLayout.addWidget(self.fileEdit, 4, 0, 1, 1)
        self.proStart = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.proStart.setObjectName("proStart")
        self.gridLayout.addWidget(self.proStart, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(357, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.fileSelcet = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.fileSelcet.setObjectName("fileSelcet")
        self.gridLayout.addWidget(self.fileSelcet, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.gridLayoutWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.gridLayout2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout2.setGeometry(QtCore.QRect(0, 0, 1080, 500))
        self.gridLayout2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout2.setSpacing(0)
        self.gridLayout2.setObjectName("gridLayout2")



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fileEdit.setText(_translate("MainWindow", "请选择想要检测的视频"))
        self.proStart.setText(_translate("MainWindow", "开始检测"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">2018141461335-冯宇帆-项目1</p></body></html>"))
        self.fileSelcet.setText(_translate("MainWindow", "选择文件"))
