# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_resultWindow(object):
    def setupUi(self, resultWindow):
        resultWindow.setObjectName("resultWindow")
        resultWindow.resize(580, 410)
        self.imageBox = QtWidgets.QGroupBox(resultWindow)
        self.imageBox.setGeometry(QtCore.QRect(180, 30, 371, 331))
        self.imageBox.setObjectName("imageBox")
        self.resultNowbox = QtWidgets.QTextBrowser(resultWindow)
        self.resultNowbox.setGeometry(QtCore.QRect(20, 40, 151, 311))
        self.resultNowbox.setObjectName("resultNowbox")

        self.retranslateUi(resultWindow)
        QtCore.QMetaObject.connectSlotsByName(resultWindow)

    def retranslateUi(self, resultWindow):
        _translate = QtCore.QCoreApplication.translate
        resultWindow.setWindowTitle(_translate("resultWindow", "Dialog"))
        self.imageBox.setTitle(_translate("resultWindow", "GroupBox"))
